[package]
name = "slmp"
license = "MIT"
authors = ["DigitalServo"]
description = "Seamless Message Protocol (SLMP) library for rust."
version = "0.1.3"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.17"
