[package]
name = "slmp"
license = "MIT"
authors = ["DigitalServo"]
description = "Library for Seamless Message Protocol (SLMP)ã€€communication"
version = "0.1.7"
edition = "2024"


[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.17"
